// Flag emoji for every country Sospana Sonke operates in (Africa, Asia, Oceania, Europe and the Americas).
// The landing page builds its country rows from the directory snapshot plus these flags,
// and every other page (companies, jobs) pulls flags from here too.
export const COUNTRY_FLAGS: Record<string, string> = {
  "South Africa": "🇿🇦",
  "Zimbabwe": "🇿🇼",
  "Botswana": "🇧🇼",
  "Namibia": "🇳🇦",
  "Mozambique": "🇲🇿",
  "Zambia": "🇿🇲",
  "Mauritius": "🇲🇺",
  "DR Congo": "🇨🇩",
  "Lesotho": "🇱🇸",
  "Eswatini": "🇸🇿",
  "Angola": "🇦🇴",
  "Nigeria": "🇳🇬",
  "Tanzania": "🇹🇿",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Côte d'Ivoire": "🇨🇮",
  "Tunisia": "🇹🇳",
  "Kenya": "🇰🇪",
  "Cameroon": "🇨🇲",
  "Egypt": "🇪🇬",
  "Togo": "🇹🇬",
  "Ethiopia": "🇪🇹",
  "Guinea": "🇬🇳",
  "Benin": "🇧🇯",
  "Ghana": "🇬🇭",
  "Uganda": "🇺🇬",
  "Gabon": "🇬🇦",
  "Sierra Leone": "🇸🇱",
  "Mali": "🇲🇱",
  "Rwanda": "🇷🇼",
  "Senegal": "🇸🇳",
  "Morocco": "🇲🇦",
  "Algeria": "🇩🇿",
  "Mauritania": "🇲🇷",
  "Niger": "🇳🇪",
  "Burkina Faso": "🇧🇫",
  "Gambia": "🇬🇲",
  "Liberia": "🇱🇷",
  "Congo": "🇨🇬",
  "Seychelles": "🇸🇨",
  "Africa": "🌍",
  "International": "🌐",
  "Cabo Verde": "🇨🇻",
  "Chad": "🇹🇩",
  "Guinea-Bissau": "🇬🇼",
  "Burundi": "🇧🇮",
  "Libya": "🇱🇾",
  "Comoros": "🇰🇲",
  "Djibouti": "🇩🇯",
  "Somalia": "🇸🇴",
  "Sao Tome and Principe": "🇸🇹",
  "South Sudan": "🇸🇸",
  "Sudan": "🇸🇩",
  "Central African Republic": "🇨🇫",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Brazil": "🇧🇷",
  "Russia": "🇷🇺",
  "India": "🇮🇳",
  "China": "🇨🇳",
  "Iran": "🇮🇷",
  "United Arab Emirates": "🇦🇪",
  "Indonesia": "🇮🇩",
  "Australia": "🇦🇺",
  "New Zealand": "🇳🇿",
  "Fiji": "🇫🇯",
  "Papua New Guinea": "🇵🇬",
  "Samoa": "🇼🇸",
  "Tonga": "🇹🇴",
  "Solomon Islands": "🇸🇧",
  "Vanuatu": "🇻🇺",
  "United Kingdom": "🇬🇧",
  "Germany": "🇩🇪",
  "France": "🇫🇷",
  "Netherlands": "🇳🇱",
  "Switzerland": "🇨🇭",
  "Sweden": "🇸🇪",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Estonia": "🇪🇪",
  "Ireland": "🇮🇪",
  "Spain": "🇪🇸",
  "Belgium": "🇧🇪",
  "Italy": "🇮🇹",
  "Norway": "🇳🇴",
  "Czechia": "🇨🇿",
  "Austria": "🇦🇹",
  "Luxembourg": "🇱🇺",
  "Lithuania": "🇱🇹",
  "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Argentina": "🇦🇷",
  "Greece": "🇬🇷",
  "Poland": "🇵🇱",
  "Turkey": "🇹🇷",
  "Portugal": "🇵🇹",
  "Bulgaria": "🇧🇬",
  "Croatia": "🇭🇷",
  "Romania": "🇷🇴",
  "Ukraine": "🇺🇦",
  "Cyprus": "🇨🇾",
  "Hungary": "🇭🇺",
  "Serbia": "🇷🇸",
  "Slovenia": "🇸🇮",
  "Georgia": "🇬🇪",
  "Armenia": "🇦🇲",
  "Singapore": "🇸🇬",
  "Israel": "🇮🇱",
  "Hong Kong": "🇭🇰",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Taiwan": "🇹🇼",
  "Thailand": "🇹🇭",
  "Philippines": "🇵🇭",
  "Vietnam": "🇻🇳",
  "Malaysia": "🇲🇾",
  "Nepal": "🇳🇵",
  "Saudi Arabia": "🇸🇦",
  "Jamaica": "🇯🇲",
  "Barbados": "🇧🇧",
  "Trinidad and Tobago": "🇹🇹",
  "Guatemala": "🇬🇹",
  "Panama": "🇵🇦",
  "Ecuador": "🇪🇨",
  "Uruguay": "🇺🇾",
  "Venezuela": "🇻🇪",
  "French Guiana": "🇬🇫",
  // Europe, from the 2026-10-07 directory.
  "Albania": "🇦🇱",
  "Andorra": "🇦🇩",
  "Belarus": "🇧🇾",
  "Bosnia and Herzegovina": "🇧🇦",
  "Holy See": "🇻🇦",
  "Iceland": "🇮🇸",
  "Kosovo": "🇽🇰",
  "Latvia": "🇱🇻",
  "Liechtenstein": "🇱🇮",
  "Malta": "🇲🇹",
  "Moldova": "🇲🇩",
  "Montenegro": "🇲🇪",
  "Slovakia": "🇸🇰",
  // Caribbean and Central America, from the 2026-10-07 directory.
  "Antigua and Barbuda": "🇦🇬",
  "Bahamas": "🇧🇸",
  "Belize": "🇧🇿",
  "Costa Rica": "🇨🇷",
  "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴",
  "El Salvador": "🇸🇻",
  "Grenada": "🇬🇩",
  "Haiti": "🇭🇹",
  "Honduras": "🇭🇳",
  "Nicaragua": "🇳🇮",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  // South America, from the 2026-10-07 directory.
  "Bolivia": "🇧🇴",
  "Guyana": "🇬🇾",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Suriname": "🇸🇷",
  // Asia and the Middle East, from the 2026-10-07 directory.
  "Afghanistan": "🇦🇫",
  "Azerbaijan": "🇦🇿",
  "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩",
  "Bhutan": "🇧🇹",
  "Brunei": "🇧🇳",
  "Cambodia": "🇰🇭",
  "Iraq": "🇮🇶",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Laos": "🇱🇦",
  "Lebanon": "🇱🇧",
  "Maldives": "🇲🇻",
  "Mongolia": "🇲🇳",
  "Oman": "🇴🇲",
  "Pakistan": "🇵🇰",
  "Palestine": "🇵🇸",
  "Qatar": "🇶🇦",
  "Sri Lanka": "🇱🇰",
  "Timor-Leste": "🇹🇱",
  "Uzbekistan": "🇺🇿",
  "Yemen": "🇾🇪",
  // Oceania, from the 2026-10-07 directory.
  "Kiribati": "🇰🇮",
  "Marshall Islands": "🇲🇭",
  "Micronesia": "🇫🇲",
  "Nauru": "🇳🇷",
  "Palau": "🇵🇼",
  "Tuvalu": "🇹🇻",
};
