// Flag emoji for every African country Sospana Sonke operates in.
// Keep this in sync with the LIVE array in app/page.tsx whenever a new country is added —
// this is the single shared source other pages (companies, jobs) pull flags from.
export const COUNTRY_FLAGS: Record<string, string> = {
  "South Africa": "🇿🇦",
  "Zimbabwe": "🇿🇼",
  "Botswana": "🇧🇼",
  "Namibia": "🇳🇦",
  "Mozambique": "🇲🇿",
  "Zambia": "🇿🇲",
  "Mauritius": "🇲🇺",
  "DR Congo": "🇨🇩",
  "Lesotho": "🇱🇸",
  "Eswatini": "🇸🇿",
  "Angola": "🇦🇴",
  "Nigeria": "🇳🇬",
  "Tanzania": "🇹🇿",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Côte d'Ivoire": "🇨🇮",
  "Tunisia": "🇹🇳",
  "Kenya": "🇰🇪",
  "Cameroon": "🇨🇲",
  "Egypt": "🇪🇬",
  "Togo": "🇹🇬",
  "Ethiopia": "🇪🇹",
  "Guinea": "🇬🇳",
  "Benin": "🇧🇯",
  "Ghana": "🇬🇭",
  "Uganda": "🇺🇬",
  "Gabon": "🇬🇦",
  "Sierra Leone": "🇸🇱",
  "Mali": "🇲🇱",
  "Rwanda": "🇷🇼",
  "Senegal": "🇸🇳",
  "Morocco": "🇲🇦",
  "Algeria": "🇩🇿",
  "Mauritania": "🇲🇷",
  "Niger": "🇳🇪",
  "Burkina Faso": "🇧🇫",
  "Gambia": "🇬🇲",
  "Liberia": "🇱🇷",
  "Congo": "🇨🇬",
  "Seychelles": "🇸🇨",
  "Cabo Verde": "🇨🇻",
  "Chad": "🇹🇩",
  "Guinea-Bissau": "🇬🇼",
  "Burundi": "🇧🇮",
  "Libya": "🇱🇾",
  "Comoros": "🇰🇲",
  "Djibouti": "🇩🇯",
  "Somalia": "🇸🇴",
  "Sao Tome and Principe": "🇸🇹",
  "South Sudan": "🇸🇸",
  "Sudan": "🇸🇩",
  "Central African Republic": "🇨🇫",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
};
